name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2022-07-28
version: '9.4.4'
project: 'drupal'
datestamp: 1659037558
